### ISSUE TITLE
Great idea! I can see a good use case

### ISSUE THREAD

**Issue by kykyi** [cmolina/rubocop-jbuilder#1]
Hi @cmolina this looks like a great idea, I was just looking today to see if there was a cop to spot N+1s in `.jbuilder` files. Is it possible to contribute yet?

**Comment by cmolina** [comment]
Hello there! 
I am not sure how to build that, wouldn't we need access to original query from the controller? What do you have in mind?

In any case, I've used Sentry.io for detecting N+1 queries in production, and bullet during development https://github.com/flyerhzm/bullet
